### PR TITLE
JooqGenerate: Add JVM Toolchain support

### PR DESCRIPTION
**Pull request by rpalcolea**
Hi folks,

Wondering if this change makes sense to support [Toolchains](https://docs.gradle.org/current/userguide/toolchains.html)

### CODE REVIEW

**Comment by etiennestuder** [comment]
Thanks, Roberto. I've wanted to do this for quite some time :-) I'll take a look next week. I need to investigate the implications on build caching and coniguration caching a bit.

**Comment by runningcode** [comment]
Hi @rpalcolea , I took a look at your changes and also wrote a test to ensure that they are compatible with the configuration cache. Unfortunately, it looks like there is the following issue with the toolchain support and configuration cache: https://github.com/gradle/gradle/issues/17785
Once the above issue is resolved we can make this change compatible with the configuration cache and we can merge it.

**Comment by zarebski-m** [comment]
@runningcode @rpalcolea It looks like the Gradle issue was fixed in 7.3.

**Comment by alextu** [comment]
Hi, I've created a new PR that I started from your branch @rpalcolea: https://github.com/etiennestuder/gradle-jooq-plugin/pull/203.

**Comment by etiennestuder** [comment]
Thanks, @rpalcolea. The toolchain functionality will be available in gradle-jooq-plugin 7.1.

**Comment by etiennestuder** [comment]
Now available: https://github.com/etiennestuder/gradle-jooq-plugin/releases/tag/v7.1

**Comment by etiennestuder** [comment]
This is fixed in the recently relased v7.1 of the gradle-jooq-plugin.

**Comment by rpalcolea** [comment]
Awesome folks! Thank you!

**Comment by etiennestuder** [comment]
@rpalcolea Note that using v7.1 (or any other v7.x) of the gradle-jooq-plugin requires using jOOQ >=3.16.x due to some backward-incompatible changes in jOOQ.

**Pull request closed without merging**
