### PR TITLE
Update to the latest jOOQ version

### PR DESCRIPTION
**Pull request by lukaseder**
The latest version right now is 3.8.4, but I wonder if there should be any hard wired version here...? Is the user able to override this default?

### CODE REVIEW

**Comment by aram535** [comment]
I tried forcing the plugin to use 3.8.4 and it seems to break code generation using the plugin.  During any operation we get a runtime error

Exception in thread "main" java.lang.VerifyError: class com.foo.generated.bar.tables.Table1 overrides final method bind.(Lorg/jooq/BindContext;)

**Comment by lukaseder** [comment]
Hello @etiennestuder and @oehme. I'm reaching out because there have been quite a few users out there in the recent past who have started using this plugin because of our official suggestion (following @oehme's PR: https://github.com/jOOQ/jOOQ/pull/5415).

Unfortunately, this means that a lot of people are "artificially" forced to use an old jOOQ version with known issues. This is very unfortunate.

Do you have any update strategy here? Any of these solutions would work:

1) Either contribute this plugin to us so we can maintain it (and we'd publish one version per jOOQ version). In this case, I'd probably need some instructions first, as I'm not very experienced in publishing stuff over Gradle. (This is my least favourite)
2) Publish one version of the plugin per jOOQ version yourself
3) Allow for very easily overriding the jOOQ version in your plugin (I don't know if that works in Gradle)

I'd love to continue suggesting this plugin as I think it does provide value to both our communities. But it only provides value if it doesn't force people to downgrade their jOOQ experience (as can be seen here: http://stackoverflow.com/q/39259263/521799)

----
See also: https://github.com/etiennestuder/gradle-jooq-plugin/pull/16

**Comment by oehme** [comment]
Hey @lukaseder,

thanks for bringing this up! I think decoupling the plugin from the jooq version is the way to go. I already opened #12 to track this. It would be a breaking change for plugin users, but probably for the better. 

In the meantime, updating to the latest jooq version is a quick workaround and I think we should do that. cc @etiennestuder 

Would you be interested in contributing such a change (isolating the jooq version used)? If so, I could give you some pointers today or tomorrow. I'll be off the next 3 weeks.

Cheers,
Stefan

**Comment by lukaseder** [comment]
> In the meantime, updating to the latest jooq version is a quick workaround and I think we should do that.

Totally agree. This is what Spring Boot does, they always refer to the latest version "automatically".

> Would you be interested in contributing such a change (isolating the jooq version used)? If so, I could give you some pointers today or tomorrow.

I'm certainly very willing to help where I can. I just don't know Gradle (and Gradle's internals) at all, so let me know how I can help

**Comment by oehme** [comment]
I'm leaving tomorrow evening, but I'll try to create a branch that shows
how I'd do it. Might not be production ready, but should at least get you
(or anyone else willing to pick it up) started.

Am 01.09.2016 14:57 schrieb "Lukas Eder" <notifications@github.com>:

**Comment by aram535** [comment]
If you can create a couple of failing tests around the failure I'm sure we can figure out something.

**Comment by ishanm** [comment]
Hi, I'm one of the users who is facing problems with the 'artificially' forced lower jooq version on the plugin. (I mentioned my issue here: http://stackoverflow.com/q/39259263/521799) Was wondering if there's anything I can do to get around this issue while the change is being worked on and merged in? Thanks!

**Comment by etiennestuder** [comment]
Superseded by https://github.com/etiennestuder/gradle-jooq-plugin/pull/20.

**Pull request closed without merging**
