### PR TITLE
Gracefully handle "XSD resource not found" errors

### PR DESCRIPTION
**Pull request by perlun**
Currently debugging this myself, which is why this more helpful error message came handy. :sweat_smile:

### CODE REVIEW

**Comment by perlun** [comment]
(I think I managed to locate the root cause for my NPE, some more details here: https://github.com/jOOQ/jOOQ/issues/12633#issuecomment-1024245898. Running out of time now at the end of the work-week, but will continue trying to fix this next week since we need this fixed for my daytime job.)

**Comment by lukaseder** [comment]
Thanks, @perlun. I agree, this should be fixed by using the `Constants.CP_CODEGEN` value, which contains the correct classpath location of the XSD file per minor release

**Comment by etiennestuder** [comment]
Thanks.

**Comment by etiennestuder** [comment]
This is fixed in the recently relased v7.0 of the gradle-jooq-plugin. The problems was due to a backward-incompatible change in jOOQ between 3.15 and 3.16.

**Pull request merged**
