### PR TITLE
Use `mainClass` property instead of deprecated `main`

### PR DESCRIPTION
**Pull request by marshallpierce**
This hopefully quiets Gradle 7's grumbling about deprecation.

### CODE REVIEW

**Comment by etiennestuder** [comment]
Thanks.

**Comment by etiennestuder** [comment]
Does not work with all 6.x versions

**Comment by marshallpierce** [comment]
Ah, I didn't think about older 6.x as I generally stay pretty current. Would it work to check the version and choose which method to invoke?

**Comment by etiennestuder** [comment]
I'll pick this up again once I upgrade my plugin's Gradle builds to 7.x.

**Comment by etiennestuder** [comment]
> Ah, I didn't think about older 6.x as I generally stay pretty current. Would it work to check the version and choose which method to invoke?

Yes, that should be doable.

**Pull request merged**
